### ISSUE TITLE
Remove inline scripts

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataDoctrineORMAdminBundle#609]
For many reasons, we should remove all scripts from the templates. We could replace them with data listerns like in the page bundle: https://github.com/sonata-project/SonataPageBundle/pull/562.
## General

Inline scripts couldn't be cached and would pollute the html output.
## Security

There is also a [security bundle](https://github.com/nelmio/NelmioSecurityBundle#content-security-policy) which introduces some interesting information about security. You could completly disable inline script via a http header to reduce possible XSS attacks. 

For more information: http://www.w3.org/TR/CSP/
## Todo

The following files contains inline scripts and should be removed in the next major release, because this is a BC break.
- [ ] https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_one_to_many.html.twig
- [ ] https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_many_association_script.html.twig
- [ ] https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_one_association_script.html.twig

**Comment by kunicmarko20** [comment]
These files have been moved to `SonataAdminBundle` can we close this issue here and you can reopen a new one there?

**Comment by jordisala1991** [comment]
Closing because of what @kunicmarko20 said.

Link to the adminbundle issue: https://github.com/sonata-project/SonataAdminBundle/issues/4031
